# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# test-access is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

#
# This file is an example of what an Invenio production environment would look like.
# Here you can find a HAProxy load balancer which redirects the traffic to the web frontend, based on nginx.
# UI application and REST API are separate.
# There are also a celery worker backend, which can be monitored using Flower, and basics services such as
# a Redis cache, a database, a message broker (RabbitMQ) and ElasticSearch.
#
version: '2.3'
services:
  # Load balancer
  lb:
    extends:
      file: docker-services.yml
      service: lb
    links:
      - frontend
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/opt/test-access/var/instance/static
    links:
      - web-ui
      - web-api
  # UI Application
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    command: pipenv run uwsgi /opt/test-access/var/instance/uwsgi_ui.ini
    image: test-access-web-ui
    ports:
      - "5000"
    volumes:
      - static_data:/opt/test-access/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: pipenv run uwsgi /opt/test-access/var/instance/uwsgi_rest.ini
    image: test-access-web-api
    ports:
      - "5001"
    volumes:
      - static_data:/opt/test-access/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "pipenv run celery worker -A invenio_app.celery --loglevel=INFO"
    image: test-access-worker
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
volumes:
  static_data:
