#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# test-access is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e


# The real bootstrap script starts 20 lines below ;-)
flags=()
while test $# -gt 0; do
    case "$1" in
        --ci)
            # We are probably inside travis, check for env variables
            if [ "$REQUIREMENTS" == "prod" ]; then
                flags=("--dev" "--ignore-pipfile")
            fi
            shift
            ;;
        *)
            # Use the flags that are passed to the script directly to install
            flags+=("$1")
            shift
            ;;
    esac
done
if [ ${#flags[0]} -eq 0 ]; then
    flags=("--dev" "--skip-lock")
fi

pipenv install ${flags[@]}


pipenv run invenio collect -v
pipenv run invenio webpack buildall
